-- Datos maestros iniciales de REXIA (Fase 0 - andamiaje).
-- Se ejecuta como parte del arranque de docker-compose (gvenzl/oracle-xe
-- procesa /container-entrypoint-initdb.d en orden alfabetico, solo la
-- primera vez que se crea el volumen de datos).
CONNECT rexia/rexia_dev_2026@//localhost:1521/XEPDB1

CREATE SEQUENCE RXA_ESPECIE_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE RXA_RAZA_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE RXA_CONCELLO_SEQ START WITH 1 INCREMENT BY 1;

CREATE TABLE RXA_ESPECIE (
  ID_ESPECIE    NUMBER(4)      NOT NULL,
  CODIGO        VARCHAR2(20)   NOT NULL,
  NOME_ES       VARCHAR2(60)   NOT NULL,
  NOME_GL       VARCHAR2(60)   NOT NULL,
  FECHA_ALTA    DATE           DEFAULT SYSDATE NOT NULL,
  USUARIO_ALTA  VARCHAR2(60)   DEFAULT USER NOT NULL,
  FECHA_MOD     DATE,
  USUARIO_MOD   VARCHAR2(60),
  CONSTRAINT PK_RXA_ESPECIE PRIMARY KEY (ID_ESPECIE),
  CONSTRAINT UK_RXA_ESPECIE_CODIGO UNIQUE (CODIGO)
);

CREATE TABLE RXA_RAZA (
  ID_RAZA       NUMBER(6)      NOT NULL,
  ID_ESPECIE    NUMBER(4)      NOT NULL,
  NOME_ES       VARCHAR2(80)   NOT NULL,
  NOME_GL       VARCHAR2(80)   NOT NULL,
  FECHA_ALTA    DATE           DEFAULT SYSDATE NOT NULL,
  USUARIO_ALTA  VARCHAR2(60)   DEFAULT USER NOT NULL,
  FECHA_MOD     DATE,
  USUARIO_MOD   VARCHAR2(60),
  CONSTRAINT PK_RXA_RAZA PRIMARY KEY (ID_RAZA),
  CONSTRAINT FK_RXA_RAZA_ESPECIE FOREIGN KEY (ID_ESPECIE) REFERENCES RXA_ESPECIE (ID_ESPECIE)
);

CREATE TABLE RXA_CONCELLO (
  ID_CONCELLO   NUMBER(6)      NOT NULL,
  CODIGO_INE    VARCHAR2(10)   NOT NULL,
  NOME          VARCHAR2(100)  NOT NULL,
  PROVINCIA     VARCHAR2(40)   NOT NULL,
  FECHA_ALTA    DATE           DEFAULT SYSDATE NOT NULL,
  USUARIO_ALTA  VARCHAR2(60)   DEFAULT USER NOT NULL,
  FECHA_MOD     DATE,
  USUARIO_MOD   VARCHAR2(60),
  CONSTRAINT PK_RXA_CONCELLO PRIMARY KEY (ID_CONCELLO),
  CONSTRAINT UK_RXA_CONCELLO_INE UNIQUE (CODIGO_INE)
);

-- Especies (enum funcional: can, gato, furon, ave, outros)
INSERT INTO RXA_ESPECIE (ID_ESPECIE, CODIGO, NOME_ES, NOME_GL) VALUES (RXA_ESPECIE_SEQ.NEXTVAL, 'CAN', 'Perro', 'Can');
INSERT INTO RXA_ESPECIE (ID_ESPECIE, CODIGO, NOME_ES, NOME_GL) VALUES (RXA_ESPECIE_SEQ.NEXTVAL, 'GATO', 'Gato', 'Gato');
INSERT INTO RXA_ESPECIE (ID_ESPECIE, CODIGO, NOME_ES, NOME_GL) VALUES (RXA_ESPECIE_SEQ.NEXTVAL, 'FURON', 'Hurón', 'Furón');
INSERT INTO RXA_ESPECIE (ID_ESPECIE, CODIGO, NOME_ES, NOME_GL) VALUES (RXA_ESPECIE_SEQ.NEXTVAL, 'AVE', 'Ave', 'Ave');
INSERT INTO RXA_ESPECIE (ID_ESPECIE, CODIGO, NOME_ES, NOME_GL) VALUES (RXA_ESPECIE_SEQ.NEXTVAL, 'OUTROS', 'Otros', 'Outros');

-- Razas de ejemplo (can y gato)
INSERT INTO RXA_RAZA (ID_RAZA, ID_ESPECIE, NOME_ES, NOME_GL) VALUES (RXA_RAZA_SEQ.NEXTVAL, 1, 'Mestizo', 'Mestizo');
INSERT INTO RXA_RAZA (ID_RAZA, ID_ESPECIE, NOME_ES, NOME_GL) VALUES (RXA_RAZA_SEQ.NEXTVAL, 1, 'Podenco Galego', 'Podenco Galego');
INSERT INTO RXA_RAZA (ID_RAZA, ID_ESPECIE, NOME_ES, NOME_GL) VALUES (RXA_RAZA_SEQ.NEXTVAL, 1, 'Pastor Alemán', 'Pastor Alemán');
INSERT INTO RXA_RAZA (ID_RAZA, ID_ESPECIE, NOME_ES, NOME_GL) VALUES (RXA_RAZA_SEQ.NEXTVAL, 2, 'Común Europeo', 'Común Europeo');

-- Concellos de ejemplo (datos publicos, no personales)
INSERT INTO RXA_CONCELLO (ID_CONCELLO, CODIGO_INE, NOME, PROVINCIA) VALUES (RXA_CONCELLO_SEQ.NEXTVAL, '15030', 'A Coruña', 'A Coruña');
INSERT INTO RXA_CONCELLO (ID_CONCELLO, CODIGO_INE, NOME, PROVINCIA) VALUES (RXA_CONCELLO_SEQ.NEXTVAL, '15078', 'Santiago de Compostela', 'A Coruña');
INSERT INTO RXA_CONCELLO (ID_CONCELLO, CODIGO_INE, NOME, PROVINCIA) VALUES (RXA_CONCELLO_SEQ.NEXTVAL, '36038', 'Pontevedra', 'Pontevedra');
INSERT INTO RXA_CONCELLO (ID_CONCELLO, CODIGO_INE, NOME, PROVINCIA) VALUES (RXA_CONCELLO_SEQ.NEXTVAL, '36057', 'Vigo', 'Pontevedra');
INSERT INTO RXA_CONCELLO (ID_CONCELLO, CODIGO_INE, NOME, PROVINCIA) VALUES (RXA_CONCELLO_SEQ.NEXTVAL, '27028', 'Lugo', 'Lugo');
INSERT INTO RXA_CONCELLO (ID_CONCELLO, CODIGO_INE, NOME, PROVINCIA) VALUES (RXA_CONCELLO_SEQ.NEXTVAL, '32054', 'Ourense', 'Ourense');

COMMIT;
EXIT;
